sudo: true
language: erlang
env:
- ST=Squeak-4.5
- ST=Squeak-Trunk
matrix:
  allow_failures:
  - env: ST=Squeak-Trunk
install:
- export PROJECT_HOME="$(pwd)"
- cd $HOME
- wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/archive/master.zip
- unzip -q builderCI.zip
- cd builderCI-*
- source build_env_vars
- ln -s $PROJECT_HOME $GIT_PATH
- "./build_image.sh"
script: "$BUILDER_CI_HOME/testTravisCI.sh"
notifications:
  slack:
    secure: BrbBsJTpjIXU7rCZzMeKC9eec0ESwzB28nUZGO7TSOjQV/inxoCPqa3umJcc609EQ2EP23miqECneywacQt/9rxatILTZxsd6kxiEZZZAtPGkTDuUz4ILmKBCzKwMjzTW9JaWMEZQ6iIYLImt6JLlmtASeXy9vLBZ+nqdg0PnZs=
