language: erlang
sudo: false

env:
  global:
    - BASELINE=PathView
  matrix:
    # - SMALLTALK="SqueakTrunk"
    - SMALLTALK="Squeak4.6"
    - SMALLTALK="Squeak4.5"

addons:
  apt:
    packages:
    # 32-bit VM
    - libc6:i386
    # UUIDPlugin
    - libuuid1:i386

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O filetreeCI.zip https://github.com/fniephaus/filetreeCI/archive/master.zip
   - unzip -q filetreeCI.zip
   - cd filetreeCI-*
   - export FILETREE_CI_HOME="$(pwd)"

script: $FILETREE_CI_HOME/run.sh

notifications:
  slack:
    secure: BrbBsJTpjIXU7rCZzMeKC9eec0ESwzB28nUZGO7TSOjQV/inxoCPqa3umJcc609EQ2EP23miqECneywacQt/9rxatILTZxsd6kxiEZZZAtPGkTDuUz4ILmKBCzKwMjzTW9JaWMEZQ6iIYLImt6JLlmtASeXy9vLBZ+nqdg0PnZs=
